#!/bin/bash

case $1 in
    powersave)
        sudo cpupower frequency-set -g powersave
        echo "Changed to powersave"
        ;;
    performance)
        sudo cpupower frequency-set -g performance
        echo "Changed to performance"
        ;;
    *)
        echo "************** Help *****************"
        echo ""
        echo "powersave - Will set your cpu to the powerave governor"
        echo "performance - Will set your cpu to the performance governor"
        echo ""
        echo "************** Help *****************"
        ;;
esac
